### ISSUE TITLE
Ask the author for help

### ISSUE THREAD

**Issue by mantouyangmeng** [joanadopp/sleep_behaviour#1]
Can you please upload the data used in the code? For example, "/2021-04-14_ethoscope_data/results" and "/Users/Joana/sleep_signature/behaviour/10x/metadata.csv" in the code.A similar file would be fine. Please, please！

**Comment by joanadopp** [comment]
Hey, sure. The db files are too big to add here, though. Can you email me (joana.dopp@kuleuven.be), then we can coordinate?
